[package]
name = "nplex"
edition = "2024.beta"

[dependencies.IotaNotarization]
git = "https://github.com/iotaledger/notarization.git"
subdir = "notarization-move"
rev = "e694e2ee8f2f9f0b9b03b843a24ff0f7bcff2930"

[addresses]
nplex = "0x0"
